---
ID: "43b8c08c-4cfc-4b37-a8a0-b05b743b2f00"
Parent: "e89179cc-4a9f-4ff2-95c4-d5bf0dd2b525"
Template: "e89179cc-4a9f-4ff2-95c4-d5bf0dd2b525"
Path: /sitecore/templates/Project/Moosend/Site/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{423BE2A8-CBF8-4F57-BD09-0AEC575E375C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220616T122849Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d5dd8c51-7a24-42ac-9ad1-a14abe8cc447"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220619T222345Z
